name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
concurrency:
  group:
    ${{ github.repository }}-${{ github.workflow }}-${{ github.event.number || github.head_ref || github.run_id || github.sha }}
  cancel-in-progress: true
env:
  JAVA_VERSION: 8
jobs:
  build:
    name: Build on Java ${{ env.JAVA_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
