name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
concurrency:
  group:
    ${{ github.repository }}-${{ github.workflow }}-${{ github.event.number || github.head_ref || github.run_id || github.sha }}
  cancel-in-progress: true
jobs:
  build:
    name: Build on Java ${{ matrix.java }} and ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
